In [2]:
import numpy as np 

primer_array = np.array(range(10))
print(primer_array)

lista = [0,1,2,3,4,5,6,7,8,9]
print(lista)


[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
print(primer_array + 100)

[100 101 102 103 104 105 106 107 108 109]


In [5]:
# print(lista + 100)

In [6]:
segundo_array = np.array(range(15,25))
print(segundo_array)

[15 16 17 18 19 20 21 22 23 24]


In [7]:
suma_arrays = primer_array + segundo_array
print(suma_arrays)

[15 17 19 21 23 25 27 29 31 33]


In [9]:
tercer_array = np.array(range(100,200))
print(tercer_array)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199]


In [11]:
# suma_arrays_dif = primer_array + tercer_array

In [13]:
# CONCATENACION 

array_concatenado = np.concatenate((primer_array,segundo_array))
print(array_concatenado)


[ 0  1  2  3  4  5  6  7  8  9 15 16 17 18 19 20 21 22 23 24]


In [15]:
array_vertical = np.vstack((primer_array,segundo_array))
print(array_vertical)

[[ 0  1  2  3  4  5  6  7  8  9]
 [15 16 17 18 19 20 21 22 23 24]]


In [16]:
print(array_vertical[0,0])

0

In [19]:
print(array_vertical[1,2])

17


In [20]:
# AGREGACIONES 

print(primer_array.mean(),segundo_array.sum())



4.5 195


In [21]:
promedio_primer = primer_array.mean()
distancia_promedio = primer_array - promedio_primer
print(distancia_promedio)

[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
